/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.showdojavao.view;

import com.mycompany.showdojavao.Model.Player;
import com.mycompany.showdojavao.controller.JogoController;
import javax.swing.JOptionPane;

/**
 *
 * @author LUISHENRIQUEPEDROSOS
 */
public class ViewPergunta1 extends javax.swing.JFrame {

    /**
     * Creates new form ViewPergunta1
     */
    public ViewPergunta1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RespostaA = new javax.swing.JButton();
        RespostaC = new javax.swing.JButton();
        RespostaD = new javax.swing.JButton();
        RespostaB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 52, 186));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("1.Qual a capital do Egito");

        RespostaA.setBackground(new java.awt.Color(255, 255, 51));
        RespostaA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaA.setText("Cairo");
        RespostaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaAActionPerformed(evt);
            }
        });

        RespostaC.setBackground(new java.awt.Color(255, 255, 51));
        RespostaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaC.setText("Brasilia");
        RespostaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaCActionPerformed(evt);
            }
        });

        RespostaD.setBackground(new java.awt.Color(255, 255, 51));
        RespostaD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaD.setText("Sidney");
        RespostaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaDActionPerformed(evt);
            }
        });

        RespostaB.setBackground(new java.awt.Color(255, 255, 51));
        RespostaB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaB.setText("Vancouver");
        RespostaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RespostaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RespostaD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RespostaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaAActionPerformed
        boolean resposta = JogoController.respostaCorreta();
        
        if(resposta == true){
            JOptionPane.showMessageDialog(null, "Certa resposta");
            this.dispose();
            new ViewPergunta2().setVisible(true);
        }
    }//GEN-LAST:event_RespostaAActionPerformed

    private void RespostaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaBActionPerformed
        boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
        }
    }//GEN-LAST:event_RespostaBActionPerformed

    private void RespostaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaCActionPerformed
                boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
        }
    }//GEN-LAST:event_RespostaCActionPerformed

    private void RespostaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaDActionPerformed
                boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
        }
    }//GEN-LAST:event_RespostaDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ViewPergunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RespostaA;
    private javax.swing.JButton RespostaB;
    private javax.swing.JButton RespostaC;
    private javax.swing.JButton RespostaD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
