/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.showdojavao.view;

import com.mycompany.showdojavao.controller.JogoController;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDROMACHADODASILVA
 */
public class ViewPergunta4 extends javax.swing.JFrame {

    /**
     * Creates new form ViewPergunta4
     */
    public ViewPergunta4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RespostaA1 = new javax.swing.JButton();
        RespostaC = new javax.swing.JButton();
        RespostaD = new javax.swing.JButton();
        RespostaB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 52, 186));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("4. Qual a proteina que pode ser");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("extraida da semente da mamona");

        RespostaA1.setBackground(new java.awt.Color(255, 255, 51));
        RespostaA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaA1.setText("Diphtheria ");
        RespostaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaA1ActionPerformed(evt);
            }
        });

        RespostaC.setBackground(new java.awt.Color(255, 255, 51));
        RespostaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaC.setText("Ricinina");
        RespostaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaCActionPerformed(evt);
            }
        });

        RespostaD.setBackground(new java.awt.Color(255, 255, 51));
        RespostaD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaD.setText("ricina ");
        RespostaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaDActionPerformed(evt);
            }
        });

        RespostaB.setBackground(new java.awt.Color(255, 255, 51));
        RespostaB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RespostaB.setText("Abrina");
        RespostaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespostaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RespostaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RespostaC, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RespostaA1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(RespostaD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RespostaB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RespostaC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RespostaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(297, 297, 297))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RespostaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaDActionPerformed
      boolean resposta = JogoController.respostaCorreta();
        
        if(resposta == true){
            JOptionPane.showMessageDialog(null, "Certa resposta");
            this.dispose();
            new ViewPergunta5().setVisible(true);
        } 
    }//GEN-LAST:event_RespostaDActionPerformed

    private void RespostaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaBActionPerformed
        boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
            new ViewDerrota().setVisible(true);
        }
    }//GEN-LAST:event_RespostaBActionPerformed

    private void RespostaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaCActionPerformed
        boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
            new ViewDerrota().setVisible(true);
        }
    }//GEN-LAST:event_RespostaCActionPerformed

    private void RespostaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespostaA1ActionPerformed
        boolean resposta = JogoController.respostaIncorreta();
        
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Errou, vai estudar seu animal");
            this.dispose();
            new ViewDerrota().setVisible(true);
        }
    }//GEN-LAST:event_RespostaA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPergunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPergunta4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RespostaA1;
    private javax.swing.JButton RespostaB;
    private javax.swing.JButton RespostaC;
    private javax.swing.JButton RespostaD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
